homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
serial:
  port: /dev/ttyACM0
devices:
  '0x00158d00046056da':
    friendly_name: farm
advanced:
  channel: 25
  log_level: debug
