#
# zigbee2mqtt
#

- file: path=/opt/zigbee2mqtt/data state=directory

- template:
    src: zigbee2mqtt.yml
    dest: /opt/zigbee2mqtt/data/configuration.yaml
  register: config

- include_role:
    name: docker-systemd-service
  vars:
    container_name: zigbee2mqtt
    container_image: koenkk/zigbee2mqtt:1.14.0
    container_volumes:
      - '/opt/zigbee2mqtt/data:/app/data'
      - '/run/udev:/run/udev:ro'
    container_host_network: true
    container_docker_pull: false
    container_devices:
      - '/dev/ttyACM0'
    container_privileged: true
    container_env:
      TZ: 'Europe/Moscow'

- systemd:
    name: zigbee2mqtt_container
    state: restarted
  when: config is changed
