- hosts: smarthome
  tasks:
    #
    # private wifi
    #

    - include_role:
        name: a0s.hostapd
      vars:
        hostapd_conf:
          - |
            interface={{ interface_wlan }}
            hw_mode=g
            channel=1
            ieee80211d=1
            country_code=BZ
            ieee80211n=1
            wmm_enabled=1
            ssid={{ interface_wlan_ssid }}
            auth_algs=1
            wpa=2
            wpa_key_mgmt=WPA-PSK
            rsn_pairwise=CCMP
            wpa_passphrase={{ interface_wlan_password }}

    - sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: true
        state: present
        reload: yes

    - systemd:
        name: network-manager
        state: stopped
        enabled: false

    - template:
        src: eth.network
        dest: /etc/systemd/network/1-eth.network

    - template:
        src: wlan.network
        dest: /etc/systemd/network/5-wlan.network

    - command: networkctl reload
    - command: systemctl restart hostapd

    #
    # mosquitto
    #

    - file: path=/opt/mosquitto/config state=directory
    - file: path=/opt/mosquitto/data state=directory
    - file: path=/opt/mosquitto/log state=directory

    - template:
        src: mosquitto.conf
        dest: /opt/mosquitto/config/mosquitto.conf
        owner: "1883"
        group: "1883"

    - include_role:
        name: docker-systemd-service
      vars:
        container_name: mosquitto
        container_image: eclipse-mosquitto:1.6.10
        container_volumes:
          - '/opt/mosquitto/config:/mosquitto/config'
          - '/opt/mosquitto/data:/mosquitto/data'
          - '/opt/mosquitto/log:/mosquitto/log'
        container_host_network: true
        container_docker_pull: false

    #
    # zigbee2mqtt
    #

    - file: path=/opt/zigbee2mqtt/data state=directory

    - template:
        src: zigbee2mqtt.yaml
        dest: /opt/zigbee2mqtt/data/configuration.yaml

    - include_role:
        name: docker-systemd-service
      vars:
        container_name: zigbee2mqtt
        container_image: koenkk/zigbee2mqtt:1.14.0
        container_volumes:
          - '/opt/zigbee2mqtt/data:/app/data'
          - '/run/udev:/run/udev:ro'
        container_host_network: true
        container_docker_pull: false
        container_devices:
          - '/dev/ttyACM0'
        container_privileged: true
        container_env:
          TZ: 'Europe/Moscow'

    #
    # avahi-daemon
    #

    - include_role:
        name: a0s.avahi
      vars:
        avahi_default_conf:
          - |
            AVAHI_DAEMON_DETECT_LOCAL=1
        avahi_conf:
          server:
            - |
              use-ipv4=yes
              use-ipv6=no
              ratelimit-interval-usec=1000000
              ratelimit-burst=1000
              allow-interfaces={{ interface_eth }}
          wide-area:
            - |
              enable-wide-area=yes
          publish:
            - |
              publish-hinfo=no
              publish-workstation=no
