#
# private wifi
#

- hosts: smarthome
  roles:
    - role: a0s.hostapd
      hostapd_conf:
        - |
          interface=wlan0
          hw_mode=g
          channel=0
          ieee80211d=1
          country_code=BZ
          ieee80211n=1
          wmm_enabled=1
          ssid={{ lookup('env','SMARTHOME_PRIVATE_WIFI_SSID') }}
          auth_algs=1
          wpa=2
          wpa_key_mgmt=WPA-PSK
          rsn_pairwise=CCMP
          wpa_passphrase={{ lookup('env','SMARTHOME_PRIVATE_WIFI_PASSWORD') }}

- hosts: smarthome
  tasks:
    - sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: true
        state: present
        reload: yes

    - template:
        src: eth0.network
        dest: /etc/systemd/network/10-eth0.network

    - template:
        src: wlan0.network
        dest: /etc/systemd/network/20-wlan0.network

    - command: networkctl reload

- hosts: smarthome
  tasks:
    - file: path=/opt/mosquitto/config state=directory
    - file: path=/opt/mosquitto/data state=directory
    - file: path=/opt/mosquitto/log state=directory

    - template:
        src: mosquitto.conf
        dest: /opt/mosquitto/config/mosquitto.conf
        owner: 1883
        group: 1883

    #
    # mosquitto
    #

    - include_role:
        name: docker-systemd-service
      vars:
        container_name: mosquitto
        container_image: eclipse-mosquitto:1.6.10
        container_volumes:
          - '/opt/mosquitto/config:/mosquitto/config'
          - '/opt/mosquitto/data:/mosquitto/data'
          - '/opt/mosquitto/log:/mosquitto/log'
        container_host_network: true
        container_docker_pull: false

    #
    # zigbee2mqtt
    #

    - file: path=/opt/zigbee2mqtt/data state=directory

    - include_role:
        name: docker-systemd-service
      vars:
        container_name: zigbee2mqtt
        container_image: koenkk/zigbee2mqtt:1.14.0
        container_volumes:
          - '/opt/zigbee2mqtt/data:/app/data'
          - '/run/udev:/run/udev:ro'
        container_host_network: true
        container_docker_pull: false
        container_devices:
          - '/dev/ttyACM0'
        container_privileged: true
        container_env:
          TZ: 'Europe/Moscow'
